server:
  port: 8080
wonderwire:
  api:
    version: v1
#Use which environment
spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    filters: config,stat,wall #,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;
    passwordCallbackClassName: com.wonderwan.wonderspace.configuration.druid.DruidDbPasswordCallback
  redis:
    database: 0
    host: 10.0.29.28
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    timeout: 10000
druid:
  resetEnable: true
  urlMappings: /druid/*
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wonderwan.wonderspace.model.entity
wonder-box:
  license:
    ttl: 5
  prefix: wonder-box.